- .github/workflows/tests.yaml
This adds a cache step to speed up github action execution.
closes #15
> Cache dependencies in pre-commit github action

- custom_components/rct_power/lib/api.py
- custom_components/rct_power/lib/device_class_helpers.py
- custom_components/rct_power/lib/entities.py
- custom_components/rct_power/lib/entity.py
- custom_components/rct_power/manifest.json
- poetry.lock
- pyproject.toml
- setup.cfg
This enables the new long-term statistics features for the relevant sensor entities in order to enable their usage on the new energy dashboard. It also upgrades some dependency versions.
closes #91
This improvement has some quirks that should be improved upon later:
- It indiscriminately adds the `SensorEntity` into the entity inheritance chain to support the new sensor properties. Since this integration doesn't use any other platforms yet, this should be fine but is a blocker for adding non-sensor entities.
- Since the data currently read from the inverter don't contain any information about the specific timestamps at which the daily, monthly and yearly counters reset, `last_reset` times are estimated using the HA host's system clock.
- The newly introduced types in the HA core indicate …
> Opt into new long-term statistics feature to support improved energy analytics

- custom_components/rct_power/lib/entities.py
- custom_components/rct_power/lib/entity.py
This adds the following entities:
- separate grid phases
- insulation resistance
It also fixes the unit on the internal inverter power readings and removes the bulky `latest_api_responses` attribute to preserve storage space.
> Add additional entities and units

- custom_components/rct_power/lib/entities.py
This exposes the energy drawn from the battery for use in the HA energy dashboard.
closes #118
> Add entity to represent consumed battery energy

- custom_components/rct_power/__init__.py
- custom_components/rct_power/lib/entities.py
- custom_components/rct_power/lib/entity.py
- custom_components/rct_power/lib/entry.py
- custom_components/rct_power/lib/schema_helpers.py
- custom_components/rct_power/lib/state_helpers.py
This adds three new entities that are calculated from the measurements:
- `"Grid Energy Production Absolute Total"`, which is the absolute value of the energy fed into the grid for usage with the energy dashboard
- `"All Generators Energy Production Total"`, which is the sum of the energy produced by generators A and B for simpler use in the energy dashboard
- `"All Generators Power"`, which is the sum of the instantaneous power of generators A and B
closes #91
closes #119
The following changes were made in order to allow for multiple (calculated) entities based on the same set of object ids:
- The unique id of each entity now includes all object ids it's derived from.
- The entity description now has an optional `unique_id` override that allows for a stable entity identity even when the …
> Add calculated entities for power generation

- custom_components/rct_power/lib/entities.py
This change the `state_class` of the "grid production" sensors to `total`, because `total_increasing` confuses the recorder if the values are negative.
closes #151
> Prevent errors due to negative values on `total_increasing` sensors

- custom_components/rct_power/lib/device_class_helpers.py
- custom_components/rct_power/lib/entity.py
- custom_components/rct_power/manifest.json
- poetry.lock
- pyproject.toml
- requirements_dev.txt
This moves the `device_class` down the `RctPowerSensorEntity` inheritance hierarchy to adapt to the fact that the `SensorEntity` now overrides the `device_class` property of the base `Entity`.
closes #170 
When the integration was installed in a Home Assistant instance for the first time before this fix but after upgrading, the recorder might have incorrectly recorded statistics using `W` and `Wh` instead of the `kW` and `kWh` expected by the Energy dashboard. In order for the entities to be selectable in the Energy configuration again, it might be necessary to use the "Fix it" feature of the "Statistics" tab in the developer tools.
Thanks to @pluskal for first reporting it and to @Benjamin410 for assisting in the investigation.
> Fix missing `device_class` from 2021.12.1 on

- custom_components/rct_power/lib/const.py
- custom_components/rct_power/lib/entities.py
- custom_components/rct_power/lib/state_helpers.py
This adds a sensor for the grid frequency that also works for systems without a power switch as requested and implemented by @k3mpaxl.
closes #134
> Add sensor for grid frequency without power switch

- hacs.json
This correctly sets the minimum [Home Assistant Core](https://github.com/home-assistant/core) version to 2021.12.0, because the recent migrations from device class and state class constants to enums are only supported since that version.
> Set minimum required HA version to 2021.12.0

- custom_components/rct_power/lib/state_helpers.py
This fixes a small bug due to which the calculated entity values `All Generators Power` and `All Generators Energy Production Total` were not rounded.
> Round the calculated sum entity values

- custom_components/rct_power/lib/entity.py
In RctPowerSensorEntity the device_class() method used to use unit_of_measurement() to get the unit of measurement for the entity. This no longer works, as with HA 2022.5.0 this implies a recursion back to unit_of_measurement() within the HA device_class() method to figure out if the entity is temperature based.
Thus using native_unit_of_measurement() instead.
> Use native_unit_of_measurement to prevent recursion.

- hacs.json
This attempts to fix the HACS action linting step by remove extraneous entries from the `hacs.json` manifest file.
> Remove extra manifest entries

- custom_components/rct_power/manifest.json
This fixes the links to the documentation and issue tracker in the component manifest file.
closes #278
> Fix documentation and issue tracker links in the manifest

- custom_components/rct_power/manifest.json
This fixes the `hassfest` action's linting error by sorting the manifest key accordingly.
> Fix manifest linting error

- custom_components/rct_power/lib/entity.py
This undoes some of the device caching that was introduced with #335 for properties that are read from the remote response. Depending on the start-up timing the device was not properly named, because the remote response hadn't been received yet.
> Avoid caching of late properties

- .github/workflows/codeql-analysis.yml
This speeds up the CodeQL workflow by not installing all project python deps during initialization. This would have been the default if this was a newer repo and follows the official recommendation of the CodeQL action.
> Speed up CodeQL workflow

- custom_components/rct_power/lib/entities.py
This corrects the unit of the new min/max battery charge sensors to be `%`.
> Set min/max soc entity unit to percent

- .github/labels.yml
- .github/release.yml
- .github/workflows/bump-and-tag-version.yml
This adds a configuration file for GitHub's native release drafting feature and a workflow to bump and tag a new version using tbump.
> Improve release automation

- custom_components/rct_power/lib/api.py
- poetry.lock
- pyproject.toml
In Python 3.11 `asyncio.timeout` was added and `asyncio.TimeoutError` became an alias for `builtins.TimeoutError`.
https://docs.python.org/3/library/asyncio-task.html#asyncio.timeout
https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError
> Remove async_timeout dependency

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- Remove unused lint dependencies: `black`, `flake8` and `reorder-python-imports`
- Remove `homeassistant-stubs`. The dependency isn't necessary anymore as `homeassistant` includes a `py.typed` file. _This hasn't always been the case which motived the creation of `homeassistant-stubs`._
- `ruff` is only used by pre-commit. I would suggest to setup https://pre-commit.ci instead. Besides providing auto-fix for PRs, this will also open PRs to update the versions in `.pre-commit-config.yaml`.
-> At the moment, those need to be kept in sync manually and are often forgotten.
-> If enabled, the `pre-commit` CI job could be removed. https://github.com/weltenwort/home-assistant-rct-power-integration/blob/30653a40484e57789c96f50aea716251bc42f835/.github/workflows/tests.yaml#L14-L17
> Remove unnecessary dev dependencies

- conftest.py
Without the explicit `return_value=None`, `patch` returns an instance of `MagicMock` / `AsyncMock`.
This leads to a lot of warnings. See https://github.com/weltenwort/home-assistant-rct-power-integration/actions/runs/13749071871/job/38447692776#step:6:46
> Fix pytest warnings

- custom_components/rct_power/__init__.py
- custom_components/rct_power/coordinator.py
- custom_components/rct_power/lib/entity.py
- custom_components/rct_power/lib/multi_coordinator_entity.py
- The coordinator should pass the config entry explicitly. Relying on the `DataUpdateCoordinator` base class will soon be deprecated.
- The coordinator base class should be stored in `<integration>/coordinator.py`
https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/common-modules/
> Minor improvements for coordinator base class

- custom_components/rct_power/__init__.py
- custom_components/rct_power/config_flow.py
- custom_components/rct_power/const.py
- custom_components/rct_power/coordinator.py
- custom_components/rct_power/init_test.py
- custom_components/rct_power/lib/api.py
- custom_components/rct_power/lib/const.py
- Store logger in a central location -> `<integration>/const.py` (I plan on moving more constants there from `api/const.py` in the future)
- Remove unnecessary startup message (see https://github.com/weltenwort/home-assistant-rct-power-integration/pull/442#discussion_r2008829623)
~_Depends on #454 to be merged first._~
> Improve logging config

- custom_components/rct_power/__init__.py
Yaml setup isn't supported, so we should remove `async_setup`.
Hassfest does even have a check for it. See the annotation on any recent CI run, e.g.
https://github.com/weltenwort/home-assistant-rct-power-integration/actions/runs/14145525178
_Technically this could break setups which have used `rct_power:` in their configs. However, as it never worked to begin with, it might be fine to remove without proper deprecation._
> Remove unused async_setup function
